#!/usr/bin/env python3
"""Builds the equirectangular land mask used by js/landmask.data.js.

Rasterizes country polygons (GeoJSON) into a 192x96 bitfield so the
globe can sample land/ocean per character cell at render time.

Usage:  python3 tools/landmask.py countries.geo.json > landmask.data.js
Data:   https://github.com/johan/world.geo.json (countries.geo.json)
Requires: pillow
"""
import json
import sys
from PIL import Image, ImageDraw

W, H = 192, 96


def project(lon: float, lat: float):
    return ((lon + 180) / 360 * (W - 1), (90 - lat) / 180 * (H - 1))


def main(path: str):
    geo = json.load(open(path))
    img = Image.new("1", (W, H), 0)
    d = ImageDraw.Draw(img)

    def poly(coords):
        pts = [project(lon, lat) for lon, lat in coords]
        if len(pts) >= 3:
            d.polygon(pts, fill=1)

    for f in geo["features"]:
        g = f["geometry"]
        if g["type"] == "Polygon":
            poly(g["coordinates"][0])
        elif g["type"] == "MultiPolygon":
            for p in g["coordinates"]:
                poly(p[0])

    px = img.load()
    rows = ["".join("1" if px[x, y] else "0" for x in range(W)) for y in range(H)]
    print("/* generated by tools/landmask.py */")
    print("window.NF_LAND = " + json.dumps(rows) + ";")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "countries.geo.json")
